[window]
opacity = 1

[window.padding]
x = 8
y = 8

[shell]
program = "/bin/zsh"
args = ["-l"]

[font]
size = 10

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[font.bold]
family = "JetBrainsMonoExtraBold Nerd Font"
style = "Extra Bold"

[font.bold_italic]
family = "JetBrainsMonoExtraBold Nerd Font"
style = "Extra Bold Italic"

[font.italic]
family = "JetBrainsMonoMedium Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMonoMedium Nerd Font"
style = "Regular"

